name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress Component Tests
        uses: cypress-io/github-action@v7
        with:
          component: true
          build: npm run build